### ISSUE TITLE
Add docs to remove passwords from console history

### ISSUE THREAD

**Issue by nuest** [StefanScherer/pwned-passwords#2]
Great little project, and cool use of Docker. Since this is for careful users, maybe you could add some docs about removing the tried passwords from the respective shell history?

For me on Ubuntu with bash I did

```
sed -i 's/docker run.*pwned-passwords.*//' ~/.bash_history
```

and then of course close the shell window.

According to [this SO post](https://stackoverflow.com/questions/8206280/delete-all-lines-beginning-with-a-from-a-file) the following should do the same on Mac (untested!):

```
sed -i '' 's/docker run.*pwned-passwords.*//' ~/.bash_history
```

**Comment by StefanScherer** [comment]
Thanks @nuest for this nice detail.

I can add this to the README, as well as this paranoid mode running the container interactively where you can search as many passwords without filling your bash history on the host machine.

```
$ docker run -it --entrypoint sh --network none -v $(pwd):/data:rw stefanscherer/pwned-passwords
/ # search secretPass
/ # search anotherSecretPass
/ # exit
```

**Comment by StefanScherer** [comment]
Added paranoid section with 20ff591c4a691cd04816a07f44df42c4eb4fcb52
